#!/bin/sh
# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.4
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

/media/common/DATAPART1/vivado/Vivado/2017.4/bin/vivado  -notrace -mode batch -source run_vivado.tcl || exit $?


